{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Research Value Classification",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/pilot-privacy/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv",

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "",

    "data_files": [
       "data_files/sentence-privacy-10.json",
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
    },

  #list_as_text is used when the input text is actually a list of texts, usually used for best-worst-scaling
    "list_as_text": {
      "text_list_prefix_type": 'None',
      "horizontal": True,
    },

    "user_config": {

      "allow_all_users": True,
      
      "users": [  ],
    },

    #defining the ways annotators entering the annotation system
    "login": {
      "type": 'url_direct',    #can be 'password' or 'url_direct'
      "url_argument": 'PROLIFIC_PID' # when the login type is set to 'url_direct', 'url_argument' must be setup for a direct url argument login
    },

    #password requirement will be removed if this is added, the associated function is still under development
    "require_no_password": True,

    #the jumping-to-id function will be disabled if "jumping_to_id_disabled" is True
    "jumping_to_id_disabled": True,

  #the navigation bar will be hidden to the annotators if "hide_navbar" is True
    "hide_navbar": True,

  # define the surveyflow of the system, set up the pages before and after the data annotation page
    "surveyflow": {
      "on": True,
      "order" : ['post_annotation'],
      # "pre_annotation": ['surveyflow/guideline.jsonl'],
      # "prestudy_passed": ['surveyflow/prestudy_pass.jsonl'],
      # "prestudy_failed": ['surveyflow/prestudy_fail.jsonl'],
      "post_annotation": ['surveyflow/experience.jsonl', 'surveyflow/end.jsonl'],
      # If set, we will automatically generate testing questions similar to the annotation instances, but explicitly ask the annotator to choose one option
      # "testing": ['surveyflow/testing.jsonl'],
    },

    # "prestudy": {
    #     "on": True,
    #     "minimum_score": 0.8,
    #     "groundtruth_key": 'whether_match',
    #     "question_key": 'Whether the presented sentences are discussing the same scientific finding',
    #     "answer_mapping": {'Yes': True, 'No': False},
    #     "pass_page": 'surveyflow/prestudy_pass.jsonl',
    #     "fail_page": 'surveyflow/prestudy_fail.jsonl'
    # },


    # "automatic_assignment": {
    #   #whether do automatic task assignment for annotators, default False.
    #   "on": True,
    #   # "output_filename": 'task_assignment.json',
    #   "sampling_strategy:": 'random',
    #   # "labels_per_instance": 5,
    #   # "instance_per_annotator": 5,
    #   # "test_question_per_annotator": 0, # you must set up the test question in surveyflow to use this function

    #   "users": [  ],
    # },


    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,
    "horizontal_key_bindings": true,


    "annotation_schemes": [
        {
          "annotation_type": "highlight",
          "name": "values",
          "description": "<p>PRIVACY & SECURITY refers to the commitment to protect user privacy and ensure robust security measures. Here are some example excerpts:</p>
            <ul>
                <li>&quot;  preserve user privacy &quot;</li>
                <li>&quot;  send encrypted emails without mistakenly revealing sensitive information &quot;</li>
                <li>&quot;  protect business-sensitive statistics &quot;</li>
                <li>&quot;  data is fully anonymized &quot;</li>
                <li>&quot;  a strong understanding of the protection provided to secure email messages &quot;</li>
                <li>&quot;  manual encryption has no effect on security &quot;</li>
                <li>&quot;  expand and improve cybersecurity education &quot;</li>
            </ul>
            <br><p>
              ATTENTION:<br>
              (1) Select PRIVACY & SECURITY then hightlight.<br>
              (2) Feel free to choose &quot;NO&quot; when there is no PRIVACY & SECURITY value in the sentence.<br>
              (3) PRIVACY & SECURITY can refer to both the inclusion and exclusion of that value. For example, the PRIVACY & SECURITY category can include both references to be careful and careless about privacy and security.<br>
              (4) PRIVACY & SECURITY is separate from other research values like performance, novelty, simplicity, theoretical grounding, efficiency, generalizability, societal implication, reproducibility, statistical significance, etc. 
            </p><br>
            Highlight ALL text spans containing the PRIVACY & SECURITY value:<br>
            (If youâ€™d like to delete a highlight you created, double click on the highlighted span.)",
          "labels": [
            'PRIVACY & SECURITY',
          ],

          # adding requirements
          "label_requirement": {"required":False},

          # If true, numbers [1-len(labels)] will be bound to each
          # label. Highlight selection annotations with more than 10 are not supported
          # with this simple keybinding and will need to use the full item
          # specification to bind all labels to keys.
          "sequential_key_binding": False,
        },
        {
            "annotation_type": "radio",
            "name": "choice_verify",
            "description": "Check your work: Does the sentence contain any PRIVACY & SECURITY value?<br><br>
                            ATTENTION: If YES, make sure you highlight PRIVACY & SECURITY value spans.",

            # adding requirements
            "label_requirement": {"required":True},

            # if you want to use multi-line textbox, turn on the text area and set the desired rows and cols of the textbox
            "labels": [
             "Yes", "No",
          ],
        },       
    ],

    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    #"html_layout": "templates/examples/fixed_keybinding_layout.html",
    "html_layout": "default",

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    # if you want to use your own template,
    # please replace the string as a path to the template
    "base_html_template": "default",
    "header_file": "default",

    # This is where the actual HTML files will be generated
    "site_dir": "default"

}
